=== Jacob-Tate/temp/resources/validation_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "temp",
    "type": "object",
    "title": "The Root Schema",
    "required": [
      "type",
      "name",
      "downloadBeforeRemove",
      "downloadBeforeInstall"
    ],
    "properties": {
      "type": {
        "$id": "#/properties/type",
        "type": "string",
        "title": "The Type Schema",
        "examples": [
          "exe",
          "files",
          "zip",
          "msi",
          "script"
        ],
        "pattern": "(?i)^(exe|zip|files|msi|script)$"
      },
      "version": {
        "$id": "#/properties/version",
        "type": "string",
        "title": "The Version Schema",
        "examples": [
          "1"
        ],
        "pattern": "(.|\\s)*\\S(.|\\s)*"
      },
      "name": {
        "$id": "#/properties/name",
        "type": "string",
        "title": "The Name Schema",
        "examples": [
          "Package Name"
        ],
        "pattern": "(.|\\s)*\\S(.|\\s)*"
      },
      "filename": {
        "$id": "#/properties/filename",
        "type": [
          "string",
          "null"
        ],
        "title": "The Filename Schema",
        "examples": [
          "C:\\filename.exe"
        ],
        "pattern": "(.|\\s)*\\S(.|\\s)*"
      },
      "filenames": {
        "$id": "#/properties/filenames",
        "type": [
          "array",
          "null"
        ],
        "title": "The Filenames Schema",
        "items": {
          "$id": "#/properties/filenames/items",
          "type": "string",
          "title": "The Items Schema",
          "examples": [
            "C:\\filename.exe"
          ],
          "pattern": "(.|\\s)*\\S(.|\\s)*"
        }
      },
      "url": {
        "$id": "#/properties/url",
        "type": [
          "string",
          "null"
        ],
        "title": "The Url Schema",
        "examples": [
          "https://www.download.filename.exe"
        ],
        "pattern": "(.|\\s)*\\S(.|\\s)*"
      },
      "urls": {
        "$id": "#/properties/urls",
        "type": [
          "array",
          "null"
        ],
        "title": "The Urls Schema",
        "items": {
          "$id": "#/properties/urls/items",
          "type": "string",
          "title": "The Items Schema",
          "examples": [
            "https://www.download.filename1.exe",
            "https://www.download.filename2.exe"
          ],
          "pattern": "(.|\\s)*\\S(.|\\s)*"
        }
      },
      "installPath": {
        "$id": "#/properties/installPath",
        "type": [
          "string",
          "null"
        ],
        "title": "The Installpath Schema",
        "examples": [
          "C:\\"
        ],
        "pattern": "^[a-zA-Z]:\\\\[\\\\\\S|*\\S]?.*$"
      },
      "installRoot": {
        "$id": "#/properties/installRoot",
        "type": [
          "string",
          "null"
        ],
        "title": "The Installroot Schema",
        "examples": [
          "C:\\"
        ],
        "pattern": "^[a-zA-Z]:\\\\[\\\\\\S|*\\S]?.*$"
      },
      "pathVar": {
        "$id": "#/properties/pathVar",
        "type": [
          "string",
          "null"
        ],
        "title": "The Pathvar Schema",
        "examples": [
          "C:\\"
        ],
        "pattern": "^[a-zA-Z]:\\\\[\\\\\\S|*\\S]?.*$"
      },
      "guid": {
        "$id": "#/properties/guid",
        "type": [
          "string",
          "null"
        ],
        "title": "The Guid Schema",
        "examples": [
          "{123}"
        ],
        "pattern": "(.|\\s)*\\S(.|\\s)*"
      },
      "installArguments": {
        "$id": "#/properties/installArguments",
        "type": [
          "string",
          "null"
        ],
        "title": "The Installarguments Schema",
        "examples": [
          "--quiet"
        ],
        "pattern": "^(.*)$"
      },
      "removeArguments": {
        "$id": "#/properties/removeArguments",
        "type": [
          "string",
          "null"
        ],
        "title": "The Removearguments Schema",
        "examples": [
          "--quiet"
        ],
        "pattern": "^(.*)$"
      },
      "removeCommands": {
        "$id": "#/properties/removeCommands",
        "type": [
          "array",
          "null"
        ],
        "title": "The Removecommands Schema",
        "items": {
          "$id": "#/properties/removeCommands/items",
          "type": "string",
          "title": "The Items Schema",
          "examples": [
            "--quiet",
            "--quiet"
          ],
          "pattern": "^(.*)$"
        }
      },
      "log": {
        "$id": "#/properties/log",
        "type": "boolean",
        "title": "The Log Schema",
        "default": false,
        "examples": [
          false
        ]
      },
      "dirArgument": {
        "$id": "#/properties/dirArgument",
        "type": [
          "string",
          "null"
        ],
        "title": "The Dirargument Schema",
        "default": "",
        "examples": [
          "DIR"
        ],
        "pattern": "^(.*)$"
      },
      "downloadBeforeRemove": {
        "$id": "#/properties/downloadBeforeRemove",
        "type": "boolean",
        "title": "The Downloadbeforeremove Schema",
        "default": false,
        "examples": [
          true
        ]
      },
      "downloadBeforeInstall": {
        "$id": "#/properties/downloadBeforeInstall",
        "type": "boolean",
        "title": "The Downloadbeforeinstall Schema",
        "default": false,
        "examples": [
          true
        ]
      }
    },
    "allOf": [
      {
        "if": {
          "properties": {
            "type": {
              "enum": [
                "files"
              ]
            }
          }
        },
        "then": {
          "allOf": [
            {
              "$ref": "#/definitions/files/filenames-requires-urls"
            },
            {
              "$ref": "#/definitions/files/filename-requires-url"
            },
            {
              "$ref": "#/definitions/files/filename-filenames-null"
            }
          ]
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "enum": [
                "zip"
              ]
            }
          }
        },
        "then": {
          "allOf": [
            {
              "$ref": "#/definitions/zip/filenames-requires-urls"
            },
            {
              "$ref": "#/definitions/zip/filename-requires-url"
            },
            {
              "$ref": "#/definitions/zip/filename-filenames-null"
            },
            {
              "$ref": "#/definitions/zip/zip-requires"
            }
          ]
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "enum": [
                "scripts"
              ]
            }
          }
        },
        "then": {}
      },
      {
        "if": {
          "properties": {
            "type": {
              "enum": [
                "exe"
              ]
            }
          }
        },
        "then": {
          "allOf": [
            {
              "$ref": "#/definitions/exe/exe-requires"
            }
          ]
        }
      },
      {
        "if": {
          "properties": {
            "type": {
              "enum": [
                "msi"
              ]
            }
          }
        },
        "then": {
          "allOf": [
            {
              "$ref": "#/definitions/msi/msi-requires"
            }
          ]
        }
      }
    ],
    "definitions": {
      "files": {
        "filenames-requires-urls": {
          "if": {
            "properties": {
              "filenames": {
                "type": "array"
              }
            }
          },
          "then": {
            "required": [
              "urls",
              "filenames",
              "installPath",
              "pathVar"
            ],
            "properties": {
              "urls": {
                "type": "array"
              },
              "filename": {
                "type": "null"
              },
              "url": {
                "type": "null"
              }
            }
          }
        },
        "filename-requires-url": {
          "if": {
            "properties": {
              "filename": {
                "type": "string"
              }
            }
          },
          "then": {
            "required": [
              "url",
              "filename",
              "installPath",
              "pathVar"
            ],
            "properties": {
              "filenames": {
                "type": "null"
              },
              "urls": {
                "type": "null"
              },
              "url": {
                "type": "string"
              }
            }
          }
        },
        "filename-filenames-null": {
          "if": {
            "properties": {
              "filename": {
                "type": "null"
              },
              "filenames": {
                "type": "null"
              }
            }
          },
          "then": {
            "properties": {
              "filename": {
                "type": "string"
              },
              "filenames": {
                "type": "array"
              }
            }
          }
        }
      },
      "zip": {
        "zip-requires": {
          "required": [
            "installPath",
            "pathVar",
            "installRoot"
          ],
          "properties": {
            "installPath": {
              "type": "string"
            },
            "pathVar": {
              "type": "string"
            },
            "installRoot": {
              "type": "string"
            }
          }
        },
        "filenames-requires-urls": {
          "if": {
            "properties": {
              "filenames": {
                "type": "array"
              }
            }
          },
          "then": {
            "required": [
              "urls",
              "filenames",
              "installPath",
              "pathVar"
            ],
            "properties": {
              "urls": {
                "type": "array"
              },
              "filename": {
                "type": "null"
              },
              "url": {
                "type": "null"
              }
            }
          }
        },
        "filename-requires-url": {
          "if": {
            "properties": {
              "filename": {
                "type": "string"
              }
            }
          },
          "then": {
            "required": [
              "url",
              "filename",
              "installPath",
              "pathVar"
            ],
            "properties": {
              "filenames": {
                "type": "null"
              },
              "urls": {
                "type": "null"
              },
              "url": {
                "type": "string"
              }
            }
          }
        },
        "filename-filenames-null": {
          "if": {
            "properties": {
              "filename": {
                "type": "null"
              },
              "filenames": {
                "type": "null"
              }
            }
          },
          "then": {
            "properties": {
              "filename": {
                "type": "string"
              },
              "filenames": {
                "type": "array"
              }
            }
          }
        }
      },
      "scripts": {},
      "exe": {
        "exe-requires": {
          "required": [
            "filename",
            "url",
            "guid",
            "installArguments",
            "removeArguments"
          ]
        },
        "properties": {
          "filename": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        }
      },
      "msi": {
        "msi-requires": {
          "required": [
            "filename",
            "url",
            "guid",
            "installArguments",
            "removeArguments"
          ]
        },
        "properties": {
          "filename": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "guid": {
            "type": "string"
          }
        }
      }
    }
  }

=== Jacob-Tate/temp/packages/utils.json
{
  "type": "files",
  "name": "utils",
  "filename": null,
  "filenames": [
    "C:\\utils\\dumpit.exe",
    "C:\\utils\\g++32.bat",
    "C:\\utils\\gcc32.bat",
    "C:\\utils\\lpath.bat",
    "C:\\utils\\setvc17-32.bat",
    "C:\\utils\\setvc17-64.bat",
    "C:\\utils\\tablen.exe"
  ],
  "url": null,
  "urls": [
    "https://azrael.digipen.edu/~mmead/www/files/utils/dumpit.exe",
    "https://azrael.digipen.edu/~mmead/www/files/utils/g++32.bat",
    "https://azrael.digipen.edu/~mmead/www/files/utils/gcc32.bat",
    "https://azrael.digipen.edu/~mmead/www/files/utils/lpath.bat",
    "https://azrael.digipen.edu/~mmead/www/files/utils/setvc17-32.bat",
    "https://azrael.digipen.edu/~mmead/www/files/utils/setvc17-64.bat",
    "https://azrael.digipen.edu/~mmead/www/files/utils/tablen.exe"
  ],
  "installPath": "C:\\utils",
  "installRoot": null,
  "pathVar": "C:\\utils",
  "guid": null,
  "installArguments": null,
  "removeArguments": null,
  "removeCommands": null,
  "log": false,
  "dirArgument": null,
  "downloadBeforeRemove": false,
  "downloadBeforeInstall": false
}

=== Jacob-Tate/temp/packages/mingw64.json
{
  "type": "zip",
  "name": "mingw64",
  "filename": "mingw64.7z",
  "filenames": null,
  "url": "https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z/download",
  "urls": null,
  "installPath": "C:\\",
  "installRoot": "C:\\mingw64",
  "pathVar": "C:\\mingw64\\bin",
  "guid": null,
  "installArguments": null,
  "removeArguments": null,
  "removeCommands": null,
  "log": false,
  "dirArgument": null,
  "downloadBeforeRemove": false,
  "downloadBeforeInstall": true
}

=== Jacob-Tate/temp/packages/DrMemory.json
{
    "type": "msi",
    "name": "Dr. Memory",
    "filename": "drmemory.msi",
	"filenames": null,
    "url": "https://github.com/DynamoRIO/drmemory/releases/download/release_1.11.0/DrMemory-Windows-1.11.0-2.msi",
	"urls": null,
	"installPath": null,
	"installRoot": null,
	"pathVar": "C:\\Program Files (x86)\\Dr. Memory\\bin",
    "guid": "{67675AD6-1FB0-4DE1-9ECF-84997515025E}",
    "installArguments": "",
	"removeArguments": null,
	"removeCommands": null,
	"log": false,
	"dirArgument": null,
	"downloadBeforeRemove": false,
	"downloadBeforeInstall": true
}

=== Jacob-Tate/temp/packages/SysInternals.json
{
    "type": "zip",
    "name": "System Internals",
    "filename": "SysinternalsSuite.zip",
    "filenames": [
        "C:\\Utils\\ADInsight.chm",
        "C:\\Utils\\ADExplorer.exe",
        "C:\\Utils\\ADInsight.exe",
        "C:\\Utils\\AccessEnum.exe",
        "C:\\Utils\\AdExplorer.chm",
        "C:\\Utils\\Autologon.exe",
        "C:\\Utils\\Autoruns.exe",
        "C:\\Utils\\Autoruns64.dll",
        "C:\\Utils\\Autoruns64.exe",
        "C:\\Utils\\Bginfo.exe",
        "C:\\Utils\\Bginfo64.exe",
        "C:\\Utils\\Cacheset.exe",
        "C:\\Utils\\Clockres.exe",
        "C:\\Utils\\Clockres64.exe",
        "C:\\Utils\\Contig.exe",
        "C:\\Utils\\Contig64.exe",
        "C:\\Utils\\Coreinfo.exe",
        "C:\\Utils\\DISKMON.HLP",
        "C:\\Utils\\DMON.SYS",
        "C:\\Utils\\Dbgview.exe",
        "C:\\Utils\\Desktops.exe",
        "C:\\Utils\\Disk2vhd.chm",
        "C:\\Utils\\DiskView.exe",
        "C:\\Utils\\Diskmon.exe",
        "C:\\Utils\\Eula.txt",
        "C:\\Utils\\FindLinks.exe",
        "C:\\Utils\\FindLinks64.exe",
        "C:\\Utils\\Listdlls.exe",
        "C:\\Utils\\Listdlls64.exe",
        "C:\\Utils\\LoadOrd.exe",
        "C:\\Utils\\LoadOrd64.exe",
        "C:\\Utils\\LoadOrdC.exe",
        "C:\\Utils\\LoadOrdC64.exe",
        "C:\\Utils\\PORTMON.CNT",
        "C:\\Utils\\PORTMON.HLP",
        "C:\\Utils\\Procmon.exe",
        "C:\\Utils\\PsExec.exe",
        "C:\\Utils\\PsExec64.exe",
        "C:\\Utils\\PsGetsid.exe",
        "C:\\Utils\\PsGetsid64.exe",
        "C:\\Utils\\PsInfo.exe",
        "C:\\Utils\\PsInfo64.exe",
        "C:\\Utils\\PsLoggedon.exe",
        "C:\\Utils\\PsLoggedon64.exe",
        "C:\\Utils\\PsService.exe",
        "C:\\Utils\\PsService64.exe",
        "C:\\Utils\\Pstools.chm",
        "C:\\Utils\\RAMMap.exe",
        "C:\\Utils\\RegDelNull.exe",
        "C:\\Utils\\RegDelNull64.exe",
        "C:\\Utils\\ShareEnum.exe",
        "C:\\Utils\\ShellRunas.exe",
        "C:\\Utils\\Sysmon.exe",
        "C:\\Utils\\Sysmon64.exe",
        "C:\\Utils\\TCPVIEW.HLP",
        "C:\\Utils\\Tcpvcon.exe",
        "C:\\Utils\\Tcpview.exe",
        "C:\\Utils\\Testlimit.exe",
        "C:\\Utils\\Testlimit64.exe",
        "C:\\Utils\\Vmmap.chm",
        "C:\\Utils\\Volumeid.exe",
        "C:\\Utils\\Volumeid64.exe",
        "C:\\Utils\\WINOBJ.HLP",
        "C:\\Utils\\Winobj.exe",
        "C:\\Utils\\ZoomIt.exe",
        "C:\\Utils\\accesschk.exe",
        "C:\\Utils\\accesschk64.exe",
        "C:\\Utils\\adrestore.exe",
        "C:\\Utils\\autoruns.chm",
        "C:\\Utils\\autorunsc.exe",
        "C:\\Utils\\autorunsc64.exe",
        "C:\\Utils\\ctrl2cap.amd.sys",
        "C:\\Utils\\ctrl2cap.exe",
        "C:\\Utils\\ctrl2cap.nt4.sys",
        "C:\\Utils\\ctrl2cap.nt5.sys",
        "C:\\Utils\\dbgview.chm",
        "C:\\Utils\\disk2vhd.exe",
        "C:\\Utils\\diskext.exe",
        "C:\\Utils\\diskext64.exe",
        "C:\\Utils\\du.exe",
        "C:\\Utils\\du64.exe",
        "C:\\Utils\\efsdump.exe",
        "C:\\Utils\\handle.exe",
        "C:\\Utils\\handle64.exe",
        "C:\\Utils\\hex2dec.exe",
        "C:\\Utils\\hex2dec64.exe",
        "C:\\Utils\\junction.exe",
        "C:\\Utils\\junction64.exe",
        "C:\\Utils\\ldmdump.exe",
        "C:\\Utils\\livekd.exe",
        "C:\\Utils\\livekd64.exe",
        "C:\\Utils\\logonsessions.exe",
        "C:\\Utils\\logonsessions64.exe",
        "C:\\Utils\\movefile.exe",
        "C:\\Utils\\movefile64.exe",
        "C:\\Utils\\notmyfault.exe",
        "C:\\Utils\\notmyfault64.exe",
        "C:\\Utils\\notmyfaultc.exe",
        "C:\\Utils\\notmyfaultc64.exe",
        "C:\\Utils\\ntfsinfo.exe",
        "C:\\Utils\\ntfsinfo64.exe",
        "C:\\Utils\\pagedfrg.exe",
        "C:\\Utils\\pagedfrg.hlp",
        "C:\\Utils\\pendmoves.exe",
        "C:\\Utils\\pendmoves64.exe",
        "C:\\Utils\\pipelist.exe",
        "C:\\Utils\\pipelist64.exe",
        "C:\\Utils\\portmon.exe",
        "C:\\Utils\\procdump.exe",
        "C:\\Utils\\procdump64.exe",
        "C:\\Utils\\procexp.chm",
        "C:\\Utils\\procexp.exe",
        "C:\\Utils\\procexp64.exe",
        "C:\\Utils\\procmon.chm",
        "C:\\Utils\\psfile.exe",
        "C:\\Utils\\psfile64.exe",
        "C:\\Utils\\pskill.exe",
        "C:\\Utils\\pskill64.exe",
        "C:\\Utils\\pslist.exe",
        "C:\\Utils\\pslist64.exe",
        "C:\\Utils\\psloglist.exe",
        "C:\\Utils\\psloglist64.exe",
        "C:\\Utils\\pspasswd.exe",
        "C:\\Utils\\pspasswd64.exe",
        "C:\\Utils\\psping.exe",
        "C:\\Utils\\psping64.exe",
        "C:\\Utils\\psshutdown.exe",
        "C:\\Utils\\pssuspend.exe",
        "C:\\Utils\\pssuspend64.exe",
        "C:\\Utils\\psversion.txt",
        "C:\\Utils\\readme.txt",
        "C:\\Utils\\regjump.exe",
        "C:\\Utils\\ru.exe",
        "C:\\Utils\\ru64.exe",
        "C:\\Utils\\sdelete.exe",
        "C:\\Utils\\sdelete64.exe",
        "C:\\Utils\\sigcheck.exe",
        "C:\\Utils\\sigcheck64.exe",
        "C:\\Utils\\streams.exe",
        "C:\\Utils\\streams64.exe",
        "C:\\Utils\\strings.exe",
        "C:\\Utils\\strings64.exe",
        "C:\\Utils\\sync.exe",
        "C:\\Utils\\sync64.exe",
        "C:\\Utils\\tcpview.chm",
        "C:\\Utils\\vmmap.exe",
        "C:\\Utils\\whois.exe",
        "C:\\Utils\\whois64.exe"
    ],
    "url": "https://download.sysinternals.com/files/SysinternalsSuite.zip",
    "urls": null,
    "installPath": "C:\\utils",
    "installRoot": "C:\\utils",
    "pathVar": "C:\\utils",
    "guid": null,
    "installArguments": null,
    "removeArguments": null,
    "removeCommands": null,
    "log": false,
    "dirArgument": null,
    "downloadBeforeRemove": false,
    "downloadBeforeInstall": true
}

=== Jacob-Tate/temp/packages/Doxygen.json
{
  "type": "exe",
  "name": "Doxygen",
  "filename": "doxygen.exe",
  "filenames": null,
  "url": "https://sourceforge.net/projects/doxygen/files/rel-1.8.6/doxygen-1.8.6-setup.exe/download",
  "urls": null,
  "installPath": null,
  "installRoot": null,
  "pathVar": "C:\\Program Files\\doxygen\\bin",
  "guid": "doxygen_is1",
  "installArguments": "/sp- /verysilent /norestart",
  "removeArguments": "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART",
  "removeCommands": null,
  "log": true,
  "dirArgument": "DIR",
  "downloadBeforeRemove": false,
  "downloadBeforeInstall": true
}

=== Jacob-Tate/temp/packages/Geany.json
{
    "type": "exe",
    "name": "Geany",
    "filename": "geany.exe",
    "filenames": null,
    "url": "https://download.geany.org/geany-1.35_setup.exe",
    "urls": null,
    "installPath": null,
    "installRoot": null,
    "pathVar": "C:\\Program Files (x86)\\Geany\\bin",
    "guid": "Geany",
    "installArguments": "/S",
    "removeArguments": "/S",
    "removeCommands": null,
    "log": true,
    "dirArgument": "D",
    "downloadBeforeRemove": false,
    "downloadBeforeInstall": true
  }

=== Jacob-Tate/temp/packages/VSBuildTools2017.json
{
  "type": "exe",
  "name": "Visual Studio Build Tools 2017",
  "filename": "vs_buildtools.exe",
  "filenames": null,
  "url": "https://aka.ms/vs/15/release/vs_buildtools.exe",
  "urls": null,
  "installPath": null,
  "installRoot": null,
  "pathVar": null,
  "guid": null,
  "installArguments": "--quiet --norestart --nocache --wait --add \"Microsoft.VisualStudio.Component.Roslyn.Compiler\" --add \"Microsoft.Component.MSBuild\" --add \"Microsoft.VisualStudio.Component.CoreBuildTools\" --add \"Microsoft.VisualStudio.Workload.MSBuildTools\" --add \"Microsoft.VisualStudio.Component.Windows10SDK\" --add \"Microsoft.VisualStudio.Component.VC.CoreBuildTools\" --add \"Microsoft.VisualStudio.Component.Static.Analysis.Tools\" --add \"Microsoft.VisualStudio.Component.VC.Tools.x86.x64\" --add \"Microsoft.VisualStudio.Component.VC.Redist.14.Latest\" --add \"Microsoft.VisualStudio.Component.Windows10SDK.17763\" --add \"Microsoft.VisualStudio.Component.VC.CMake.Project\" --add \"Microsoft.VisualStudio.Component.TestTools.BuildTools\" --add \"Microsoft.VisualStudio.Component.VC.Tools.ARM\" --add \"Microsoft.VisualStudio.Workload.VCTools\" --add \"Microsoft.VisualStudio.Component.NuGet.BuildTools\" --add \"Microsoft.Net.Component.4.5.TargetingPack\"",
  "removeArguments": null,
  "removeCommands": [
    "--quiet --norestart --nocache --wait --remove \"Microsoft.VisualStudio.Component.Roslyn.Compiler\" --remove \"Microsoft.Component.MSBuild\" --remove \"Microsoft.VisualStudio.Component.CoreBuildTools\" --remove \"Microsoft.VisualStudio.Workload.MSBuildTools\" --remove \"Microsoft.VisualStudio.Component.Windows10SDK\" --remove \"Microsoft.VisualStudio.Component.VC.CoreBuildTools\" --remove \"Microsoft.VisualStudio.Component.Static.Analysis.Tools\" --remove \"Microsoft.VisualStudio.Component.VC.Tools.x86.x64\" --remove \"Microsoft.VisualStudio.Component.VC.Redist.14.Latest\" --remove \"Microsoft.VisualStudio.Component.Windows10SDK.17763\" --remove \"Microsoft.VisualStudio.Component.VC.CMake.Project\" --remove \"Microsoft.VisualStudio.Component.TestTools.BuildTools\" --remove \"Microsoft.VisualStudio.Component.VC.Tools.ARM\" --remove \"Microsoft.VisualStudio.Workload.VCTools\" --remove \"Microsoft.VisualStudio.Component.NuGet.BuildTools\" --remove \"Microsoft.Net.Component.4.5.TargetingPack\""
  ],
  "log": false,
  "dirArgument": null,
  "downloadBeforeRemove": true,
  "downloadBeforeInstall": true
}
